### ISSUE TITLE
Can I get any usage example of this library?

### ISSUE THREAD

**Issue by tanishiking** [davenverse/googleapis-http4s#290]
Hi, first of all, thank you for providing this library!

Could someone please share an example of how to use any GCP libraries?

I've been attempting to communicate with Firestore using `http4s-grpc-google-cloud-firestore-v1`, but I'm encountering an issue where it fails with a `java.util.NoSuchElementException` before sending the request to Firestore.

context: I'm attempting to develop example app that consumes some GCP application on CloudRun based on https://github.com/ChristopherDavenport/scala-native-ember-example/pull/7

```scala
//> using scala 3
//> using dep "org.http4s::http4s-ember-client:0.23.23"
//> using dep "org.typelevel::log4cats-slf4j:2.6.0"
//> using dep "io.chrisdavenport::http4s-grpc-google-cloud-firestore-v1:3.15.2+0.0.6"

import cats.syntax.all._
import cats.effect._
import org.http4s._

import org.typelevel.log4cats.LoggerFactory
import org.typelevel.log4cats.slf4j.Slf4jFactory
import org.http4s.client.Client
import org.http4s.ember.client.EmberClientBuilder

import com.google.firestore.v1.firestore.Firestore
import com.google.firestore.v1.document.Document
import com.google.firestore.v1.firestore.GetDocumentRequest
import com.google.firestore.v1.firestore.GetDocumentRequest.ConsistencySelector

object Main extends IOApp:
  override def run(args: List[String]): IO[ExitCode] =
    val projectId: String = args(0)
    val databaseId: String = args(1)
    createClient().use { client =>
      val firestore = Firestore.fromClient(
        client,
        Uri
          .fromString("https://firestore.googleapis.com")
          .getOrElse(throw new RuntimeException("invalid firestore uri"))
      )
      val docId = "1"
      firestore.getDocument(
        GetDocumentRequest.of(
          name = createDocumentName(projectId, databaseId, "jokes", docId),
          mask = None,
          consistencySelector = ConsistencySelector.Empty
        ),
        Headers.empty
      ).flatMap { doc =>
        IO.println(doc)
      } >> ExitCode.Success.pure[IO]
    }
  
  private implicit val loggerFactory: LoggerFactory[IO] =
    Slf4jFactory.create[IO]

  def createDocumentName(
      projectId: String,
      databaseId: String,
      collectionId: String,
      jokeId: String
  ): String = {
    val documentPath = s"projects/$projectId/databases/$databaseId/documents"
    s"$documentPath/$collectionId/$jokeId"
  }
  
  def createClient(): Resource[IO, Client[IO]] =
    EmberClientBuilder
      .default[IO]
      .withHttp2
      .build
  
  def createFirestoreClient(client: Client[IO]): Firestore[IO] =
    Firestore.fromClient[IO](
      client,
      Uri
        .fromString("https://firestore.googleapis.com")
        .getOrElse(throw new RuntimeException("invalid firestore uri"))
    )
```

```sh
❯ scala-cli run main.scala -- tanishiking-dev ember
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.util.NoSuchElementException
        at fs2.Stream$CompileOps.lastOrError$$anonfun$1$$anonfun$1(Stream.scala:4918)
        at scala.Option.fold(Option.scala:263)
        at fs2.Stream$CompileOps.lastOrError$$anonfun$1(Stream.scala:4918)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at rethrow$extension @ fs2.Compiler$Target.compile$$anonfun$1(Compiler.scala:157)
        at as @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.connect$1$$anonfun$1$$anonfun$1(SocketGroupPlatform.scala:76)
        at get @ org.http4s.ember.core.h2.H2Client$.impl$$anonfun$1(H2Client.scala:343)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Pull$.goCloseScope$1$$anonfun$1$$anonfun$3(Pull.scala:1217)
        at update @ org.http4s.ember.core.h2.H2Connection.readLoop$$anonfun$1(H2Connection.scala:549)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```

**Comment by armanbilge** [comment]
Cool!

> but I'm encountering an issue where it fails with a `java.util.NoSuchElementException` before sending the request to Firestore.

How did you determine that the error occurs before the request is sent? I was thinking the error was originating from here, but that's the response decoder.

https://github.com/davenverse/http4s-grpc/blob/305ea92d0af8bb5ddf9aca377d5292a105c2722b/core/src/main/scala/org/http4s/grpc/codecs/Messages.scala#L20

Is authentication needed to access this API?

**Comment by tanishiking** [comment]
Nevermind, I was misunderstanding, and it seems we get an error on receive the response 😅 
After adding Logger middleware to the client, it says:

```
HTTP/2.0 POST https://firestore.googleapis.com/google.firestore.v1.Firestore/GetDocument Headers(te: trailers, grpc-encoding: identity, grpc-accept-encoding: identity, Content-Type: application/grpc+proto) body="<
:projects/tanishiking-dev/databases/ember/documents/jokes/1"
HTTP/2.0 404 Not Found Headers(date: Fri, 27 Oct 2023 05:43:51 GMT, content-type: text/html; charset=UTF-8, server: ESF, content-length: 1602, x-xss-protection: 0, x-frame-options: SAMEORIGIN, x-content-type-options: nosniff, alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000) body="<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/google.firestore.v1.Firestore/GetDocument</code> was not found on this server.  <ins>That’s all we know.</ins>
```

It's 404 probably because it doesn't have credentials, I gonna play around with it with emulator for now :)

**Comment by tanishiking** [comment]
it seems i need to learn https://googleapis.github.io/HowToRPC.html 🤓

**Comment by tanishiking** [comment]
Here's a progress https://github.com/tanishiking/http4s-firestore now I'm receiving [RESOURCE_PROJECT_INVALID](https://cloud.google.com/java/docs/reference/proto-google-common-protos/latest/com.google.api.ErrorReason) 🤔

**Comment by tanishiking** [comment]
Okay, it worked at least on JVM :tada:

```scala
//> using scala 3
//> using dep "org.http4s::http4s-ember-client:0.23.23"
//> using dep "io.chrisdavenport::http4s-grpc-google-cloud-firestore-v1:3.15.2+0.0.6"

import cats.syntax.all._
import cats.effect._
import org.http4s._

import org.http4s.client.Client
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.client.middleware.Logger

import com.google.firestore.v1.firestore.Firestore
import com.google.firestore.v1.document.Document
import com.google.firestore.v1.firestore.GetDocumentRequest
import com.google.firestore.v1.firestore.GetDocumentRequest.ConsistencySelector
import com.google.firestore.v1.firestore.CreateDocumentRequest
import com.google.firestore.v1.document.Value
import com.google.firestore.v1.document.Value.ValueTypeOneof

object Main extends IOApp:
  override def run(args: List[String]): IO[ExitCode] =
    val projectId: String = args(0)
    val accessToken: String = args(1)
    createClient().use { rawClient =>
      val client = Logger[IO](
        logHeaders = true,
        logBody = true,
        redactHeadersWhen = _ => false,
        logAction = Some(msg => IO.println(msg))
      )(rawClient)
      val firestore = Firestore.fromClient(
        client,
        Uri
          .fromString("https://firestore.googleapis.com")
          .getOrElse(throw new RuntimeException("invalid firestore uri"))
      )
      val docId = System.currentTimeMillis().toString
      firestore
        .createDocument(
          CreateDocumentRequest.of(
            parent = s"projects/$projectId/databases/(default)/documents",
            collectionId = "jokes",
            documentId = docId,
            document = Some(Document.of(
              name = "",
              fields = Map(
                "joke" -> Value.of(
                  ValueTypeOneof.StringValue("joke")
                )
              ),
              createTime = None,
              updateTime = None
            )),
            mask = None
          ),
          Headers.of(
            headers.Authorization(
              Credentials.Token(AuthScheme.Bearer, accessToken)
            ),
            headers.`Content-Type`(
              new MediaType("application", "grpc")
            )
          )
        )
        .flatMap { doc =>
          IO.println(doc)
        } >> ExitCode.Success.pure[IO]
    }

  def createClient(): Resource[IO, Client[IO]] =
    EmberClientBuilder
      .default[IO]
      .withHttp2
      .build
```

**Comment by armanbilge** [comment]
@tanishiking I was looking more closely at the guide you linked. I'm a little confused, I wonder if you're actually invoking the "fallback" instead of the "true" gRPC API 🤔 

https://googleapis.github.io/HowToRPC.html#grpc-fallback-experimental

**Comment by armanbilge** [comment]
> * We needed to request to the services with `headers.`Content-Type`(new MediaType("application", "application/x-protobuf"))`

Unfortunately this also seems correct. If you look at the logs for the original request in https://github.com/davenverse/googleapis-http4s/issues/290#issuecomment-1782333901 you can see it is already including the correct header `Content-Type: application/grpc+proto`.

**Comment by tanishiking** [comment]
> I was looking more closely at the guide you linked. I'm a little confused, I wonder if you're actually invoking the "fallback" instead of the "true" gRPC API 🤔

Yeah, I was also thinking about it, but I'm not sure how can we force to use "true" gRPC API 🤔 

> Unfortunately this also seems incorrect. If you look at the logs for the original request in https://github.com/davenverse/googleapis-http4s/issues/290#issuecomment-1782333901 you can see it is already including the correct header Content-Type: application/grpc+proto.

Yes, that statement turned out to be incorrect. However, we still need to set `ContentType` as `application/grpc` or `application/x-protobuf` it seems. Otherwise (with default `Content-Type: application/grpc+proto`) we get `  <p><b>404.</b> <ins>That’s an error.</ins><p>The requested URL <code>/$rpc/google.firestore.v1.Firestore/CreateDocument</code> was not found on this server.  <ins>That’s all we know.</ins>`

**Comment by tanishiking** [comment]
It seems like the fallback protocol is like https://github.com/googleapis/googleapis.github.io/blob/bcb-to-fb/examples/rpc/rust/src/main.rs that RPC using normal HTTP POST 

```rust
    let mut res = client.post("https://language.googleapis.com/$rpc/google.cloud.language.v1.LanguageService/AnalyzeEntities")
		.header(ContentType(Mime::from_str("application/x-protobuf").unwrap()))
		.header(XGoogApiKey(google_api_key.to_owned()))
		.body(serialized_bytes)
		.send().unwrap();
```

So, if http4s-grpc doesn't fallback to the HTTP call, we're using gRPC on the [above example](https://github.com/davenverse/googleapis-http4s/issues/290#issuecomment-1784606670) maybe? (I'm quite new to gRPC and not sure how can we confirm we're communicating over gRPC :bow:)

```
❯ scala-cli main.scala -- tanishiking-dev $(gcloud auth application-default print-access-token)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
HTTP/2.0 POST https://firestore.googleapis.com/$rpc/google.firestore.v1.Firestore/CreateDocument Headers(te: trailers, grpc-encoding: identity, grpc-accept-encoding: identity, Authorization: Bearer ..., Content-Type: application/grpc) body="a
1698678199810"shiking-dev/databases/(default)/documentsjokes
joke�joke"
HTTP/2.0 200 OK Headers(content-disposition: attachment, content-type: application/grpc, date: Mon, 30 Oct 2023 15:03:20 GMT, alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000) body="y
Jprojects/tanishiking-dev/databases/(default)/documents/jokes/1698678199810
joke�joke
        ����ع��"
               ����ع��"
Document(projects/tanishiking-dev/databases/(default)/documents/jokes/1698678199810,Map(joke -> Value(StringValue(joke),UnknownFieldSet(Map()))),Some(Timestamp(1698678200,524279000,UnknownFieldSet(Map()))),Some(Timestamp(1698678200,524279000,UnknownFieldSet(Map()))),UnknownFieldSet(Map()))
```

**Comment by armanbilge** [comment]
Well, it's complicated, because gRPC itself is defined over HTTP/2 😅  So I'm not entirely sure how the fallback is different from that.

---

I believe the `Content-Type: application/grpc+proto` is required by the gRPC specification. So if you are not using that, probably you are not actually using gRPC?

https://github.com/grpc/grpc/blob/c2f49c2d3b236bf04f9da786c6b5b412271df7dc/doc/PROTOCOL-HTTP2.md#example

---

> Otherwise (with default `Content-Type: application/grpc+proto`) we get ` <p><b>404.</b> <ins>That’s an error.</ins><p>The requested URL <code>/$rpc/google.firestore.v1.Firestore/CreateDocument</code> was not found on this server. <ins>That’s all we know.</ins>`

I'm very suspicious about this `/$rpc/` thing, I wonder if this is the true gRPC endpoint which is why it does not accept the correctly-formed request.

> For most Google APIs, the BaseUrl looks like `https://language.googleapis.com/$rpc` (experimental: this format may change in the future).

It seems strange if true gRPC is using an experimental URL format. But it would make sense for "gRPC Fallback (Experimental)" to be use an experimental URL format.

---

Sorry, I'm mostly throwing mud at your code without answers of my own 😅  Thanks for your efforts to actually make this stuff work 🙏

We may need to study an official Google library to see how its invoking the gRPCs.

**Comment by tanishiking** [comment]
> I believe the Content-Type: application/grpc+proto is required by the gRPC specification. So if you are not using that, probably you are not actually using gRPC?
> It seems strange if true gRPC is using an experimental URL format. But it would make sense for "gRPC Fallback (Experimental)" to be use an experimental URL format.

Hm, that makes sense.

Anyway, it seems we need to study from an official Google library as you mentioned 😅 

> Sorry, I'm mostly throwing mud at your code without answers of my own

No worries! I really appreciate having someone to talk to about this issue 😄 

---

BTW, I made an another sloppy example that programmatically authenticate GCP using service account key (instead of `gcloud auth application-default print-access-token`) https://github.com/tanishiking/http4s-firestore-auth

**Comment by tanishiking** [comment]
Awesome! Are you planning to deprecate the `gcp4s` for `googleapis-http4s-runtime`?

**Comment by armanbilge** [comment]
> Are you planning to deprecate the `gcp4s`

Currently that library has a couple other modules in it that I haven't figured out what to do with yet. For example it supports BigQuery APIs that are not available over gRPC.

**Comment by i10416** [comment]
linking https://github.com/davenverse/googleapis-http4s-runtime/issues/20

**Comment by i10416** [comment]
Example with googleapis-runtime:
 
```scala
//> using scala "2.13.12"
//> using repositories "sonatype-s01:snapshots"
//> using dep "dev.i10416::http4s-googleapis-runtime:0.0-20544fa-SNAPSHOT"
//> using dep "org.http4s::http4s-core:0.23.25"
//> using dep "org.http4s::http4s-ember-client:0.23.25"
//> using dep "org.typelevel::cats-effect:3.5.2"
//> using dep "io.chrisdavenport::http4s-grpc-google-cloud-firestore-v1:3.15.2+0.0.6"
import org.http4s.syntax.all._
import com.google.firestore.v1.firestore.Firestore
import com.google.firestore.v1.document.Document
import com.google.firestore.v1.firestore.GetDocumentRequest
import com.google.firestore.v1.firestore.GetDocumentRequest.ConsistencySelector
import com.google.firestore.v1.firestore.CreateDocumentRequest
import com.google.firestore.v1.document.Value
import com.google.firestore.v1.document.Value.ValueTypeOneof

import cats.effect._
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.googleapis.runtime.auth.ApplicationDefaultCredentials
import com.google.firestore.v1.firestore.ListDocumentsRequest
import org.http4s.Headers
import org.http4s.headers.`Content-Type`
import org.http4s.MediaType
import org.http4s.headers.Authorization
import org.http4s.Credentials
import org.http4s.AuthScheme

object Main extends IOApp {
  private val projectId: String = ??? // your GCP project id
  private val parentCollection: String = ???
  private val collectionId: String =  ???
  def run(args: List[String]): IO[ExitCode] = EmberClientBuilder
    .default[IO]
    .withHttp2
    .build
    .use { client =>
      for {
        oauth2 <- ApplicationDefaultCredentials(client)
        tkn <- oauth2.get
        f = Firestore.fromClient(client, uri"https://firestore.googleapis.com")
        response <- f.listDocuments(
          ListDocumentsRequest(
            parent =
              s"projects/$projectId/databases/(default)/documents/$parentCollection",
            collectionId = collectionId,
            pageSize = 10
          ),
          Headers(
            Authorization(
              Credentials.Token(AuthScheme.Bearer, tkn.token)
            ),
            `Content-Type`(
              new MediaType("application", "grpc")
            )
          )
        )
        _ <- IO.println(response)
      } yield ()

    }
    .handleErrorWith(IO.println(_))
    .as(ExitCode.Success)
}

```

**Comment by i10416** [comment]
For someone interested in Scala GCP integration:

When working on some APIs, you must set x-goog-request-params" header and values.

It is described in Google AIP 4222

https://github.com/alin04/aip/blob/d2b14beff570d660e1562b987b7fa21c131cdfde/aip/client-libraries/4222.md?plain=1#L24
